---
kind: pipeline
name: build-debug

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init --recursive

- name: build
  image: microsoft/dotnet:2-sdk
  commands:
    - dotnet publish "Jellyfin.Server" --configuration Debug --output "../ci/ci-debug"

---
kind: pipeline
name: build-release

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init --recursive

- name: build
  image: microsoft/dotnet:2-sdk
  commands:
    - dotnet publish "Jellyfin.Server" --configuration Release --output "../ci/ci-release"

